services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - my_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_springboot_backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - my_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_react_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge